import type {
  PlacementBand,
  PlacementExamBank,
  PlacementExamKey,
  PlacementQuestionSeed,
} from './placementExamData';

const EN_DME_SCALE: PlacementBand[] = [
  { min: 0, max: 12, label: 'Book 1' },
  { min: 13, max: 24, label: 'Book 2' },
  { min: 25, max: 36, label: 'Book 3' },
  { min: 37, max: 48, label: 'Book 4' },
  { min: 49, max: 60, label: 'Book 5' },
];

const EN_DME_QUESTIONS: PlacementQuestionSeed[] = [
  { id: 'q-001', prompt: 'Berlin is a small country.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-002', prompt: "There are seven letters in the word 'radio'.", options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-003', prompt: "The opposite of 'first' is 'last'.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-004', prompt: 'We eat breakfast in the evening.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-005', prompt: 'A mouse is a big animal.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-006', prompt: 'Knives and forks are made of metal.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-007', prompt: 'People are happy when they sleep badly.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-008', prompt: "It's necessary to pay when we buy something in a shop.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-009', prompt: "It's easy to drive on a foggy day.", options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-010', prompt: 'A horse is stronger than an elephant.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-011', prompt: 'Diet and exercise are important if you want to be healthy.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-012', prompt: "We wouldn't be in danger if this building were in flames.", options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-013', prompt: 'People can change the laws of nature.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-014', prompt: 'Kind people have a lot of enemies.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-015', prompt: "When you want to buy something, it's good to compare different products before choosing one.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-016', prompt: "'Sidewalk' and 'pavement' both mean the same thing.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-017', prompt: 'A flatmate is a person who works with us in the same corporation.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-018', prompt: 'A commuter is a person who travels long distances to work every day.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-019', prompt: 'Some people are superstitious about walking under a ladder.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-020', prompt: "'I would have got injured if I had been with them in the car' means that I was injured in a car crash.", options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-021', prompt: 'You can book a hotel room if there are no vacant rooms.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-022', prompt: 'Your teeth will decay if you neglect to brush them.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-023', prompt: 'Greedy people are seldom satisfied with what they get.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-024', prompt: "A person who remains unconscious after an accident shouldn't be moved.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-025', prompt: 'In some countries the law recognizes smacking a child as assault.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-026', prompt: "A child's health is a common anxiety of a parent.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-027', prompt: 'We get rough winds in a mild climate.', options: ['true', 'false'], answer: 'false', wrongPenalty: -1 },
  { id: 'q-028', prompt: "The opposite of 'tough' is 'tender'.", options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-029', prompt: 'The stroke of lightning comes before the thunder.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-030', prompt: 'Light bulbs often need replacement.', options: ['true', 'false'], answer: 'true', wrongPenalty: -1 },
  { id: 'q-031', prompt: 'Am I ... the window?', options: ['open', 'closing', 'close'], answer: 'closing', wrongPenalty: 0 },
  { id: 'q-032', prompt: '... you have a red box?', options: ['Does', 'Do', 'Are'], answer: 'Do', wrongPenalty: 0 },
  { id: 'q-033', prompt: '... like your town?', options: ['You', 'You do', 'Do you'], answer: 'Do you', wrongPenalty: 0 },
  { id: 'q-034', prompt: 'Are there ... students in the classroom?', options: ['any', 'some', 'a'], answer: 'any', wrongPenalty: 0 },
  { id: 'q-035', prompt: 'I can ... somebody in the corridor.', options: ['to hear', 'hearing', 'hear'], answer: 'hear', wrongPenalty: 0 },
  { id: 'q-036', prompt: 'A train is ... than a car.', options: ['heaviest', 'heavier', 'lighter'], answer: 'heavier', wrongPenalty: 0 },
  { id: 'q-037', prompt: '... you at school yesterday?', options: ['Was', 'Are', 'Were'], answer: 'Were', wrongPenalty: 0 },
  { id: 'q-038', prompt: 'When ... World War Two start?', options: ['did', 'do', 'was'], answer: 'did', wrongPenalty: 0 },
  { id: 'q-039', prompt: 'I will cook soup if you ... some meat and vegetables.', options: ['will buy', 'buy', 'buying'], answer: 'buy', wrongPenalty: 0 },
  { id: 'q-040', prompt: 'I have ... to New York twice.', options: ['been', 'be', 'doing'], answer: 'been', wrongPenalty: 0 },
  { id: 'q-041', prompt: 'If you ... me a thousand pounds, I would be happy.', options: ['offered', 'would offer', 'will offer'], answer: 'offered', wrongPenalty: 0 },
  { id: 'q-042', prompt: 'She may ... everything.', options: ['saying', 'to say', 'say'], answer: 'say', wrongPenalty: 0 },
  { id: 'q-043', prompt: "You can't buy many things if you have too ... money.", options: ['little', 'a little', 'few'], answer: 'little', wrongPenalty: 0 },
  { id: 'q-044', prompt: 'My parents were ... the flat on Saturday evening.', options: ['cleaned', 'cleaning', 'clean'], answer: 'cleaning', wrongPenalty: 0 },
  { id: 'q-045', prompt: 'Computers are ... in most offices.', options: ['using', 'use', 'used'], answer: 'used', wrongPenalty: 0 },
  { id: 'q-046', prompt: 'It is worth making the ... to learn a foreign language.', options: ['trial', 'attempt', 'try'], answer: 'attempt', wrongPenalty: 0 },
  { id: 'q-047', prompt: 'Some people often try to ... their problems instead of solving them.', options: ['dry', 'sink', 'drown'], answer: 'drown', wrongPenalty: 0 },
  { id: 'q-048', prompt: 'He was really ... after having cycled uphill for 30 minutes.', options: ['exhausted', 'exhausting', 'tired'], answer: 'exhausted', wrongPenalty: 0 },
  { id: 'q-049', prompt: "'You mustn't put it here' He ... me to put it there.", options: ['advised', 'ordered', 'forbade'], answer: 'forbade', wrongPenalty: 0 },
  { id: 'q-050', prompt: 'The city officials want to reduce ... by encouraging drivers to use the public transport.', options: ['exhaust fumes', 'acid rains', 'ozone layer'], answer: 'exhaust fumes', wrongPenalty: 0 },
  { id: 'q-051', prompt: 'He canceled the reservation at ... notice and had to pay the whole amount.', options: ['postponed', 'late', 'short'], answer: 'short', wrongPenalty: 0 },
  { id: 'q-052', prompt: "Susan has been ... from work for spoiling their customers' satisfaction.", options: ['dismissed', 'left', 'sending'], answer: 'dismissed', wrongPenalty: 0 },
  { id: 'q-053', prompt: 'They were refused ... to the club as they were under age.', options: ['entrance', 'exit', 'admission'], answer: 'admission', wrongPenalty: 0 },
  { id: 'q-054', prompt: 'It is high time Tom ... something about his attitude towards other drivers.', options: ['did', 'do', 'done'], answer: 'did', wrongPenalty: 0 },
  { id: 'q-055', prompt: 'We will start looking for a new flat to rent as soon as we ... the old one.', options: ['will have sold', 'will sell', 'sell'], answer: 'sell', wrongPenalty: 0 },
  { id: 'q-056', prompt: 'According to the law, a person is assumed innocent until ... guilty.', options: ['proved', 'proven', 'proof'], answer: 'proven', wrongPenalty: 0 },
  { id: 'q-057', prompt: "Is 'acquire' the synonym of ...?", options: ['gain', 'exact', 'retail'], answer: 'gain', wrongPenalty: 0 },
  { id: 'q-058', prompt: 'The company sells furniture designed to be ... at home.', options: ['assembled', 'put up', 'built'], answer: 'assembled', wrongPenalty: 0 },
  { id: 'q-059', prompt: 'A first-... kit is an essential piece of equipment in a vehicle.', options: ['help', 'aid', 'treatment'], answer: 'aid', wrongPenalty: 0 },
  { id: 'q-060', prompt: 'They tried to stop their dog from ... at the table.', options: ['begging', 'wagging', 'bursting'], answer: 'begging', wrongPenalty: 0 },
];

function createBank(key: PlacementExamKey, ageScope: string): PlacementExamBank {
  return {
    key,
    title: 'English Placement Test (DME 3rd Edition - INT)',
    languageId: 'en',
    ageScope,
    sourceFileName: 'DME_3rd_placement_test_INT.pdf',
    placementBands: EN_DME_SCALE.map((item) => ({ ...item })),
    questions: EN_DME_QUESTIONS.map((item) => ({
      ...item,
      options: item.options ? [...item.options] : undefined,
    })),
  };
}

export const ENGLISH_DME_BANKS = {
  'en-adult': createBank('en-adult', '18+'),
} as const satisfies Partial<Record<PlacementExamKey, PlacementExamBank>>;
