export interface LegalDocumentData {
  slug: string;
  title: string;
  shortDescription: string;
  kind: string;
  pdfPath: string;
  paragraphs: string[];
}

export const LEGAL_DOCUMENTS: LegalDocumentData[] = [
  {
    "slug": "gizlilik-politikasi",
    "title": "Gizlilik Politikası",
    "shortDescription": "Veri gizliliği, bilgi güvenliği ve web sitesi kullanım sorumluluklarına ilişkin temel ilkeler.",
    "kind": "Politika",
    "pdfPath": "/legal/teachera-gizlilik-politikasi.pdf",
    "paragraphs": [
      "Teachera Eğitim Kurumları Limited Şirketi öğrenci, öğrenci adayı ve velilerinin verdiği tüm bilgilerin gizliliğini korumak amacıyla aşağıda belirtilen temel kuralları benimsemiştir:",
      "• Öğrenci , öğrenci adayı ve velilerimizden sadece ürün/hizmet başvuruları ile ilgili olan ve kendilerine hizmet",
      "sunabilmemiz için gerekli gördüğümüz bilgileri talep ederiz.",
      "• Öğrenci, öğrenci adayı ve velilerimizin güvenliği ve www.teachera.com.tr üzerinden giriş yapılan bilgilerin",
      "gizliliğini korumak amacıyla Teachera Eğitim Kurumları Limited Şirketi ‘nin sisteminin ve altyapısının en güvenilir seviyede tutulmasını sağlayacak bütün önlemler alınmıştır.",
      "• Öğrenci, öğrenci adayı ve velilerimizin www.teachera.com.tr adresine ürün/hizmet başvurusu ve bilgi güncelleme",
      "amaçlı girmiş oldukları bilgilerin diğer internet kullanıcıları tarafından görüntülenmesini engellemek için gerekli bütün önlemler alınmıştır.",
      "• Öğrenci, öğrenci adayı ve velilerimizin kurumumuz ile paylaştığı bilgilere izinsiz ulaşım, Teachera Eğitim",
      "Kurumları Limited Şirketi personeli de dahil olmak üzere kısıtlanmıştır. Söz konusu bilgiler öğrenci, öğrenci adayları ve velilerimizin onayı dışında ya da yasal bir yükümlülük altında bulunulmadığı sürece herhangi bir üçüncü şahıs, kurum ve kuruluş ile paylaşılmaz.",
      "• Teachera Eğitim Kurumları Limited Şirketi.’nin destek hizmetler almak amacıyla farklı kuruluşlarla çalışması",
      "durumunda, bu firmaların kurumumuz gizlilik standartlarına ve şartlarına uymaları sağlanır.",
      "• Gizlilik Politikamız’da yer alan taahhütlerimiz yalnızca www.teachera.com.tr adresimiz için geçerli olup,",
      "www.teachera.com.tr linkleri verilen diğer web sitelerini kapsamamaktadır. Söz konusu diğer web sitelerinin kullanımında o sitelere ait gizlilik politikası ve kullanım şartları geçerlidir.",
      "• Teachera Eğitim Kurumları Limited Şirketi www.teachera.com.tr adresi üzerinden reklam, banner, içerik veya",
      "başka bir maksat ile geçilen diğer web sitelerinin bilgi kullanımı, etik ilkeleri, gizlilik politikaları, nitelik ve servis k alitesi ile bu sitelerde oluşabilecek herhangi bir maddi/manevi zarar ve kayıplardan sorumlu değildir.",
      "• Gerek www.teachera.com.tr de linkleri verilen diğer web sitelerindeki, gerekse de diğer internet sitelerine",
      "bağlantıların riski, kullanıcıya aittir. Bu sitelerde verilen bilgilerin doğruluğu ile bu sitelerden verilen diğer bağlantıların nitelikleri Teachera Eğitim Kurumları Limited Şirketi’ tarafından araştırılmamış ve doğrulanmamıştır.",
      "Genel Kullanım Şartları ve Sorumluluğun Sınırlandırılması www.teachera.com.tr internet sitesine girmekle aşağıda belirtilen şartları kabul etmiş olursunuz.",
      "Bu nedenle öncelikle “Genel Kullanım Şartları ve Sorumluluğun Sınırlandırılması” ile ilgili aşağıda belirtilen şartları dikkatle okumanızı rica ederiz.",
      "Belirtilen şartları kabul etmiyorsanız lütfen Teachera Eğitim Kurumları Limited Şirketi İnternet Sitesi’ni ve herhangi bir sayfasını kullanmayınız, ürün ve hizmet başvurusunda bulunmayınız.",
      "• Bu internet sitesinde yer alan bilgi, materyal ve bunların düzenlenmesi konusundaki telif hakları, tescilli marka,",
      "patent, fikri ve diğer mülkiyet hakları Teachera Eğitim Kurumları Limited Şirketi’ne aittir. Herhangi bir kişi/kuruluş, önceden Teachera Eğitim Kurumları‘nın yazılı iznini almaksızın, bu internet sitesinin belirli bir kısmını başka bir web sitesinde veya sair yerde kullanamaz veya başka bir web sitesinden bağlantı kuramaz.",
      "• Bu internet sitesinde verilen her türlü bilgiler ve materyaller “olduğu gibi”, “mevcut olduğu şekilde”",
      "sağlanmaktadırlar. Teachera Eğitim Kurumları Limited Şirketi’ bu bilgilerin doğruluğunu ve yeterliliğini garanti etmemekte olup, bu bilgilerdeki hatalar ya da eksiklikler nedeniyle doğabilecek her türlü sorumluluğu açık bir şekilde reddetmektedir. Bu bilgilerle üçüncü şahısların haklarının ihlal edilmemesi; mülkiyet, satılabilirlik ve/veya belirli bir amaç için uygunluğa ilişkin garantiler dahil ancak bunlarla sınırlı kalmamak kaydıyla, zımnen, açıkça ya da yasal olarak hiçbir garanti vermemektedir.",
      "• İşbu internet sitesinin kullanımı sırasında herhangi bir performans arızası, hata, eksiklik, kesinti, kusur, işletme",
      "ve/veya nakilde gecikme, bilgisayar virüsü, hat ve/veya sistem arızası gibi sebeplerle ortaya çıkan doğrudan ya da dolaylı zarar, ziyan ve masraflar da dahil ancak bunlarla sınırlı olmamak üzere hiçbir zarar ve ziyandan, Teachera Eğitim Kurumları Limited Şirketi ve/veya çalışanları, bu tür bir zarar ve ziyan olasılığından haberdar olsalar dahi, sorumlu değildirler.",
      "• Teachera Eğitim Kurumları Limited Şirketi bu internet sitesinde yer alan bütün ürün ve hizmetleri, sayfaları,",
      "bilgileri, görsel unsurları ve burada yer alan şartları önceden bildirimde bulunmadan değiştirme hakkını saklı tutar.",
      "• Bu internet sitesinin belirli bölüm ve sayfalarında yukarıda belirtilenlere ek şartlar öngörülmüş olabilir. Burada",
      "belirtilen genel şartlar ile ek şartlar arasında çelişki olması halinde ilgili bölüm ve sayfaya ilişkin ek şartlar uygulanır.",
      "• Bu internet sitesinin kullanımından doğacak ihtilaflarda, kanunlar ihtilafına ilişkin hükümleri dikkate alınmaksızın",
      "Türk Hukuku uygulanır. İhtilafların hallinde, kanunen yetkili mahkemelerin yanı sıra Konya Mahkeme ve İcra Daireleri de yetkilidir."
    ]
  },
  {
    "slug": "cocuklarin-gizlilik-politikasi",
    "title": "Çocukların Gizlilik Politikası",
    "shortDescription": "18 yaş altı kullanıcıların verilerinin korunması ve veli/vasilere yönelik bilgilendirme esasları.",
    "kind": "Politika",
    "pdfPath": "/legal/cocuklarin-gizlilik-politikasi.pdf",
    "paragraphs": [
      "COCUKLARIN GIZLILIK POLITIKASI Veri Sorumlusu: Teachera Egitim Kurumlari Limited Sirketi Adres: Musalla Baglari Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selcuklu / Konya Telefon: 0332 236 80 66 E-posta: kvkk@teachera.com.tr Web: www.teachera.com.tr",
      "1. Kapsam",
      "Bu politika, 18 yas altindaki cocuklarin ve veli/vasilerinin web sitesi, basvuru formlari ve iletisim kanallari araciligiyla paylastigi verilerin korunmasi icin uygulanir.",
      "2. Islenen Veri Kategorileri",
      "Kimlik ve iletisim bilgileri (ad, soyad, telefon, e-posta), egitimle ilgili talep bilgileri ve web sitesi kullanimina iliskin teknik veriler islenebilir.",
      "3. Isleme Amaclari",
      "Basvuru ve kayit sureclerini yurutmek, veli ile iletisim kurmak, egitim planlamasi yapmak, hukuki yukumlulukleri yerine getirmek ve bilgi guvenligini saglamak amaclariyla veri islenir.",
      "4. Cocuklara Ozel Ilkeler",
      "Cocuklara ait veriler icin veri minimizasyonu uygulanir; zorunlu olmayan veri talep edilmez.",
      "Cocuklara yonelik pazarlama iletisimleri veli onayi olmaksizin gerceklestirilmez.",
      "5. Aktarim ve Saklama",
      "Veriler, mevzuatin izin verdigi olcude hizmet saglayicilara veya yetkili kurumlara aktarilabilir. Veriler, isleme amaci icin gerekli sure kadar saklanir ve sure sonunda mevzuata uygun sekilde silinir, yok edilir veya anonimlestirilir.",
      "6. Haklar ve Basvuru",
      "KVKK madde 11 kapsamindaki haklarinizi kullanmak icin kvkk@teachera.com.tr adresine basvurabilirsiniz. Basvurular mevzuatta ongorulen surelerde sonuclandirilir."
    ]
  },
  {
    "slug": "cerez-politikasi",
    "title": "Çerez Politikası",
    "shortDescription": "Web sitesinde kullanılan çerez türleri, amaçları ve tercih yönetimine ilişkin açıklamalar.",
    "kind": "Politika",
    "pdfPath": "/legal/teachera-cerez-politikasi.pdf",
    "paragraphs": [
      "Teachera Eğitim Kurumları L imited Şirketi olarak web sitelerimizi ziyaretleriniz sırasında deneyiminizi geliştirmek için çerezlerden faydalanıyoruz. Bu teknolojilerin kullanımı başta 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVK Kanunu”) olmak üzere tabi olduğumuz mevzuata uygun şekilde ger çekleştirilmektedir. Kişisel verilerinizin kurumumuz tarafından işlenmesi hakkında daha detaylı bilgi almak için www.teachera.com.tr adresinde yer alan “ Kişisel Verilerin Korunması” içeriğini okumanızı tavsiye ederiz.",
      "Çerez Nedir?",
      "Çerez, size daha hızlı ve güvenli bir deneyim sağlamak amacıyla internet sitelerinin bilgisayarınıza bıraktığı tanımlama dosyalarıdır. Sitemizi tekrar ziyaret ettiğinizde bilgisayarınızı tanımamızı, ihtiyaçlarınıza uygun ve size özel hizmetleri d aha çabuk sunmamızı sağlarlar.",
      "Neden Çerez Kullanıyoruz?",
      "• İnternet sitemiz üzerinde daha sonraki ziyaretlerinizde kullanıcı deneyimlerini iyileştirmek,",
      "• İnternet sitemizin fonksiyonlarını iyileştirmemize yardımcı olacak analizleri ve istatistikleri oluşturmak,",
      "• Hesaplama araçlarına girilen bilgileri kayıt altında tutmak,",
      "• Kullanım alışkanlıklarınız çerçevesi de kurumumuz ürün ve hizmetlerimizi tercihlerinize uygun olacak şekilde",
      "sizlere sunabilmek, internet sitemizi kişiselleştirebilmek,",
      "• Daha etkin pazarlama faaliyetleri gerçekleştirmek amacıyla çerez kullanıyoruz.",
      "İnternet sitemizde “Geçici Çerezler” ve “Kalıcı Çerezler” olmak üzere iki tür çerez kullanılmaktadır.",
      "Geçici çerezler sitemizde geçirdiğiniz süre boyunca aktif olurlar ve internet sitesinden ayrıldığınızda bilgisayarınızdan silinirler.",
      "Kalıcı çerezler ise internet sitemizi ziyaret ettiğinizde oluşturulur, siz silinceye veya süreleri doluncaya kadar sabit diskinizde kalırlar. Kalıcı çerezler size ayarlarınız ile uyumlu kişiselleştirilmiş bir deneyim sunmamız için yardımcı olurla r.",
      "Kalıcı ve Geçici Çerezler bilgisayarınızda veya dosyalarınızda depolanan kişisel verileriniz de dahil olmak üzere kullanıcılara ait gizli bilgileri toplamazlar.",
      "Kullandığımız Çerez Türleri ve Açıklamaları Oturum Çerezleri İnternet sayfaları arasında bilgi taşınması ve kullanıcı tarafından girilen bilgilerin sistemsel olarak hatırlanması gibi çeşitli özelliklerden faydalanmaya olanak sağlayan çerezlerdir ve internet sitesine ait fonksiyonların düzgün bir şekilde işleyebilmesi için gereklidir.",
      "Performans Çerezleri Sayfaların ziyaret edilme frekansı, olası hata iletileri, kullanıcıların ilgili sayfada harcadıkları toplam zaman ile birlikte siteyi kullanım desenleri konularında bilgi toplayan çerezlerdir. İnternet sitesinin performansını artırma amacıyla kullanılmaktadır.",
      "Fonksiyonel Çerezler Kullanıcıya kolaylık sağlanması amacıyla önceden seçili olan seçeneklerin hatırlatılmasını sağlayan çerezlerdir.",
      "Kullanıcılara gelişmiş internet özellikleri sağlanmasını hedeflemektedir.",
      "Operasyonel Amaçlı Çerezler Sistemlerinin idaresi ve güvenliğinin sağlanması amacıyla, bu sitedeki fonksiyonlardan yararlanmayı sağlayan veyahut düzensiz davranışları tespit eden çerezlerdir.",
      "Reklam ve Üçüncü Taraf Çerezleri Üçüncü parti tedarikçilere ait çerezlerdir. İnternet sitesindeki bazı fonksiyonların kullanımına ve reklam takibinin yapılmasına olanak sağlamaktadır Çerezlerin Kullanımını Nasıl Kontrol Edebilirsiniz?",
      "Teachera Eğitim Kurumları Limited Şirketi kullandığı çerezlerde öğrencilerine, velilerine, kullanıcılarına ait gizli bilgileri saklamaz.İnternet tarayıcıları, çerezleri otomatik olarak kabul edecek şekilde ön tanımlıdır. Ancak çerezleri dilediğiniz gib i kontrol edebilir veya silebilirsiniz.",
      "Çerezleri yönetmek tarayıcıdan tarayıcıya farklılık gösterir. Çerezlerin bilgisayarınızda saklanmasını istemiyorsanız tarayıcınızın ayarlar kısmından çerez kullanım tercihlerinizi değiştirebilirsiniz. Çerez yönetim ayarları tarayıcıdan tarayıcıya farklılık göstermekte ve modern tarayıcıların yardım menüleri altında çerezlere ilişkin detaylı bilgiler yer almaktadır.",
      "Çerezlerinizi yönetmek için aşağıdaki linkleri kullanabilirsiniz. Çerezleri tamamen engellemeyi tercih ederseniz Teachera Eğitim Kurumları Limited Şirketi ait internet siteleri düzgün çalışmayabilir ya da size özel fırsatları göremeyebilirsiniz.",
      "Adobe Analytics http://www.adobe.com/uk/privacy/opt-out.htmlBu bağlantı yeni sekmede açılacak.",
      "AOL https://help.aol.com/articles/restore-security-settings-and-enable-cookie-settings-on-browserBu bağlantı yeni sekmede açılacak.",
      "Countly http://count.ly/legal/cookie-policyBu bağlantı yeni sekmede açılacak.",
      "Google Adwords https://support.google.com/ads/answer/2662922?hl=enBu bağlantı yeni sekmede açılacak.",
      "Google Analytics https://tools.google.com/dlpage/gaoptoutBu bağlantı yeni sekmede açılacak.",
      "Google Chrome http://www.google.com/support/chrome/bin/answer.py?hl=en&answer=95647Bu bağlantı yeni sekmede açılacak.",
      "Internet Explorer https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookiesBu bağlantı yeni sekmede açılacak.",
      "MozillaFirefox http://support.mozilla.com/en-US/kb/CookiesBu bağlantı yeni sekmede açılacak.",
      "Opera http://www.opera.com/browser/tutorials/security/privacy/Bu bağlantı yeni sekmede açılacak.",
      "SMPL. https://www.hellosmpl.com/privacy-policy/Bu bağlantı yeni sekmede açılacak.",
      "Teachera Eğitim Kurumları Limited Şirketi Çerez Politikası ile İlgili Önemli Hatırlatmalar",
      "• Teachera Eğitim Kurumları Limited Şirketi gerekli gördüğü durumlarda, kullandığı çerezleri kullanmaktan",
      "vazgeçebilir, bunların türlerini veya fonksiyonlarını değiştirebilir veya internet sitesine yeni çerezler ekleyebilir.",
      "• Teachera Eğitim Kurumları Limited Şirketi’nin çerez kullanımında yapacağı değişiklikler Çerez Politikası’na",
      "yansıtılacaktır. Çerez Politikası’nı belirli zamanlarda inceleyerek, çerez kullanımı ile ilgili bilgi edinmenizi tavsiye ederiz.",
      "• Teachera Eğitim Kurumları Limited Şirketi çerezleri Gizlilik Politikası kapsamında kullanmaktadır ve gerekli",
      "durumlarda Çerez Politikası’nı değiştirme hakkını saklı tutar.",
      "Veri Sahibi Olarak Haklarınız Nelerdir?",
      "KVK Kanunu’nun 11. maddesi uyarınca veri sahipleri;",
      "• Kişisel veri işlenip işlenmediğini öğrenme,",
      "• Kişisel verileri işlenmişse buna ilişkin bilgi talep etme,",
      "• Kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,",
      "• Yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme,",
      "• Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme ve bu kapsamda yapılan",
      "işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,",
      "• KVK Kanunu ve ilgili diğer kanun hükümlerine uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren",
      "sebeplerin ortadan kalkması hâlinde kişisel verilerin silinmesini veya yok edilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,",
      "• İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir",
      "sonucun ortaya çıkmasına itiraz etme,",
      "• Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini talep etme",
      "haklarına sahiptir.",
      "Söz konusu haklarınıza ilişkin taleplerinizi kvkk@teachera.com.tr Mail adresinden 0332 236 80 66 numaralı İletişim Merkezimizi arayarak veya şubelerimizden iletmeniz halinde başvurularınız en kısa sürede ve en geç 30 (otuz) gün içerisinde değerlendirilerek sonuçlandırılacaktır."
    ]
  },
  {
    "slug": "ebeveyn-muvafakatname",
    "title": "Ebeveyn Muvafakatname",
    "shortDescription": "Veli/vasi onayı gerektiren süreçler için rıza ve bilgilendirme metni.",
    "kind": "Taahhüt / Onay",
    "pdfPath": "/legal/ebeveyn-muvafakatname.pdf",
    "paragraphs": [
      "EBEVEYN MUVAFAKATNAME Veri Sorumlusu: Teachera Egitim Kurumlari Limited Sirketi Adres: Musalla Baglari Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selcuklu / Konya Telefon: 0332 236 80 66 E-posta: kvkk@teachera.com.tr Web: www.teachera.com.tr",
      "1. Muvafakat Veren Veli/Vasi Bilgileri",
      "Ad Soyad: ____________________ T.C. Kimlik No: ____________________ Telefon: ____________________ E-posta: ____________________ Adres: ______________________________________________________",
      "2. Kursiyer Cocuk Bilgileri",
      "Ad Soyad: ____________________ Dogum Tarihi: ____________________",
      "3. Acik Riza Beyani",
      "Velisi/vasisi oldugum cocuguma ait kimlik, iletisim, egitim ve olcum-degerlendirme verilerinin;",
      "kayit, planlama, egitim sunumu, iletisim, raporlama ve mevzuattan dogan yukumluluklerin yerine getirilmesi amaclariyla islenmesine acik riza veriyorum.",
      "Kisisel verilerin, gerekli durumlarda hukuki yukumlulukler ve hizmet surecinin yurutulmesi kapsaminda yurt icindeki yetkili kurum/kuruluslar ve hizmet saglayicilarla paylasilabilecegini biliyor ve kabul ediyorum.",
      "4. Bilgilendirme",
      "Bu muvafakatname, KVKK kapsaminda bilgilendirilmis irade ile duzenlenmistir. Acik rizami diledigim zaman geri cekebilecegim tarafima bildirilmiştir.",
      "5. Tarih ve Imza",
      "Tarih: ____ / ____ / ______ Veli/Vasi Imza: ____________________"
    ]
  },
  {
    "slug": "yurt-disina-aktarim-acik-riza",
    "title": "Yurt Dışına Aktarım Açık Rıza Metni",
    "shortDescription": "Dijital altyapı süreçlerinde yurt dışına veri aktarımına ilişkin açık rıza beyanı.",
    "kind": "Açık Rıza",
    "pdfPath": "/legal/yurt-disina-aktarim-acik-riza-metni.pdf",
    "paragraphs": [
      "YURT DISINA AKTARIM ACIK RIZA METNI Veri Sorumlusu: Teachera Egitim Kurumlari Limited Sirketi Adres: Musalla Baglari Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selcuklu / Konya Telefon: 0332 236 80 66 E-posta: kvkk@teachera.com.tr Web: www.teachera.com.tr",
      "1. Kapsam ve Amac",
      "Bu acik riza metni, dijital altyapi, bulut depolama, iletisim ve operasyon araclari kullanimi nedeniyle kisisel verilerin yurt disina aktarilabilmesine iliskin bilgilendirme amaciyla hazirlanmistir.",
      "2. Aktarilabilecek Veri Kategorileri",
      "Kimlik, iletisim, talep/egitim kayitlari, teknik erisim ve iletisim loglari gibi veriler;",
      "hizmetin niteligine gore islenebilir ve aktarilabilir.",
      "3. Acik Riza Beyani",
      "KVKK kapsaminda tarafima yapilan bilgilendirme dogrultusunda, yukarida belirtilen veri kategorilerimin hizmetin sunulmasi ve sureclerin yurutulmesi amaciyla yurt disinda bulunan hizmet saglayicilara aktarilmasina acik riza veriyorum.",
      "4. Geri Cekme ve Basvuru",
      "Acik riza beyanimi diledigim zaman geri cekebilecegimi biliyorum. Geri cekme talepleri kvkk@teachera.com.tr adresine iletilebilir.",
      "5. Onay",
      "Ad Soyad: ____________________ Tarih: ____ / ____ / ______ Imza: ____________________"
    ]
  },
  {
    "slug": "whatsapp-acik-riza-metni",
    "title": "WhatsApp Açık Rıza Metni",
    "shortDescription": "WhatsApp iletişim kanalında bilgilendirme ve iletişim süreçlerine dair açık rıza metni.",
    "kind": "Açık Rıza",
    "pdfPath": "/legal/whatsapp-acik-riza-metni.pdf",
    "paragraphs": [
      "WHATSAPP ACIK RIZA METNI Veri Sorumlusu: Teachera Egitim Kurumlari Limited Sirketi Adres: Musalla Baglari Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selcuklu / Konya Telefon: 0332 236 80 66 E-posta: kvkk@teachera.com.tr Web: www.teachera.com.tr",
      "1. Iletisim Kanali ve Kapsam",
      "Bu metin, kurum tarafindan WhatsApp kanali uzerinden bilgilendirme, hatirlatma ve musteri temsilcisi iletisimlerinin yurutulmesine iliskin acik riza kapsamindadir.",
      "2. Islenebilecek Veriler",
      "Telefon numarasi, ad-soyad, mesaj icerikleri, randevu/egitim tercihleri ve iletisim kayitlari islenebilir.",
      "3. Acik Riza Beyani",
      "Kurumun benimle WhatsApp uzerinden iletisim kurmasina ve bu kanalda paylastigim kisisel verilerin iletisim sureclerinin yurutulmesi amaciyla islenmesine acik riza veriyorum.",
      "4. Geri Cekme Hakki",
      "Acik riza beyanimi diledigim zaman geri cekebilirim. Geri cekme talebimi kvkk@teachera.com.tr adresine iletebilirim.",
      "5. Onay",
      "Ad Soyad: ____________________ Tarih: ____ / ____ / ______ Imza: ____________________"
    ]
  },
  {
    "slug": "musteri-aydinlatma-metni",
    "title": "Müşteri Aydınlatma Metni",
    "shortDescription": "Kursiyer/veli verilerinin işlenme amaçları, hukuki sebepleri ve haklara ilişkin aydınlatma metni.",
    "kind": "Aydınlatma",
    "pdfPath": "/legal/musteri-aydinlatma-metni.pdf",
    "paragraphs": [
      "KİŞİSEL VERİLERİN KORUNMASI KANUNU HAKKINDA VELİ / KURSİYER AYDINLATMA/BİLGİLENDİRME METNİ Doküman No FR-KVKK-11 Ilk Yayın Tarihi 13.03.2023 Revizyon No - Revizyon Tarihi - 1 Veri Sorumlusu ve İlgili Kişi Bilgisi 6698 sayılı Kişisel Verilerin Korunması Kanunu'na göre hazırlanmış olup, firması, sizinle ilgili kişisel verileri işlemesi, v eri işleme amaçlarını belirlemesi, veri işleme sisteminin kurulması ve işletilmesi sebebiyle veri sorumlusudur TEACHERA EĞİTİM KURUMLARI LİMİTED ŞİRKETİ tarafından, kişisel verisi işlenen gerçek kişiler, kanun tarafından ilgili kişi olarak kabul edilmektedir.",
      "Kanunun Aydınlatma Yükümlülüğünü düzenleyen 10'ncu maddesine göre, veri sorumluları, kişisel verilerini işledikleri gerçek kişileri, veri işleme ile ilgili konularda bilgilendirmekle yükümlüdür.",
      "Bu metin, ilgili kişi olarak sizi bilgilendirmeye yönelik hazırlanmış olup, ilgili kişinin (veri sahibinin) ve veri sorumlusunun hak ve yükümlülüklerini içermektedir.",
      "VERİ SORUMLUSU Unvanı TEACHERA EĞİTİM KURUMLARI LİMİTED ŞİRKETİ Posta Adresi Musalla Bağları Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selçuklu / Konya Telefon 0332 236 80 66 E-posta kvkk@teachera.com.tr İnternet Adresi www.teachera.com.tr Velinin ve kursiyer kişisel verileri,",
      "• Yazılı veya elektronik ortamda yayınlanan başvuru formları ile,",
      "• Veli ve Kursiyer Kimlik Bilgileri: T.C. kimlik no, ad, soyad,, doğum yeri/tarihi, pasaport numarası, imza(varsa), medeni",
      "hal ile",
      "• Özlük Bilgileri: Cinsiyet, vatandaşlık bilgisi, öğrenim durumu",
      "• İletişim ve Adres Bilgisi: Telefon numaraları, E -posta adresleri, ulaşılabilecek 3. Kişilerin numaraları ile Adresler (Ev",
      "adresi, iş adresi) ile",
      "• Mesleki Bilgiler: Unvan, deneyim, çalıştığı kurum ile",
      "• Çeşitli sosyal medya kanalları üzerinden kurumumuz adına işletilen hesaplar kanalı ile",
      "• Elektronik posta adresleri üzerinden yürütülen yazışmalar, gönderilen kısa mesajlar ve multi medya mesajları, bilgi",
      "formları da dâhil ve sair iletişim yöntemleri ile her türlü iletişim kanalları aracılığı ile",
      "• Kursiyer ve Veli adayları tarafından iletilen bilgilerin doğruluğunu teyit etmek amacıyla yapılan kontroller ile",
      "kurumumuz tarafından yapılan araştırmalar ile toplanmaktadır.",
      "Kişisel Verilerin Kimlere ve Hangi Amaçla Aktarılabileceği Alıcı Grubu Aktarım Amacı Yetkili kamu kurum ve kuruluşları Gerektiğinde kamera kayıtlarının Emniyet Müdürlüğü ile paylaşılması Sağlık bakanlığının talep ettiği listeyi paylaşmak Kursiyer, veli ve kurum çalışanlarının sağlığını yükseltmek ve farkındalık oluşturmak amacıyla eksik görülen ya da talep edilen eğitim planlamasının oluşturulup sunulması Tedarikçi(Bankalar, mali müşavirler) Banka kanalı ile kayıt yaptıracakların ilgili bilgilerinin bankaya verilmesi Tedarikçi (mali müşavir) Finansal ve mali tabloların YMM şirketi tarafından onaylanması.",
      "Tedarikçi (E-posta hizmeti tedarikçisi) Kurum içi ve Kurum dışı e-posta kanalıyla yapılan iletişimin sağlanabilmesi amacıyla mali belgelerin ve kursiyer hakkındaki bilgilerin iletilmesi teachera KİŞİSEL VERİLERİN KORUNMASI KANUNU HAKKINDA VELİ / KURSİYER AYDINLATMA/BİLGİLENDİRME METNİ Doküman No FR-KVKK-11 Ilk Yayın Tarihi 13.03.2023 Revizyon No - Revizyon Tarihi - 2 Tedarikçi- Yurtdışı (Kurs otomasyon şirketi tedarikçisi) Sistemin çalışabilmesi amacıyla veri girişinin sağlanması Sistem içi etüt planlamalarının takip edilmesi Anketlerin üst yönetime sunulması Duyuru yayınlama Tedarikçi (İletişim şirketi) Kurs hakkında bilgilendirme mesajlarının veli ve personele sms ile gönderilmesi Tedarikçi (Ölçme- değerlendirme uzmanı) Performans yönetim rapor ve anketlerin analizi ve üst yönetime sunulması Web Sitesi Ziyaretçileri/ Sosyal medya kullanıcıları Kurs tanıtımının yapılması Etkinlik / duyuru yayınlanması Anketlerin üst yönetime sunulması Kişisel Verilerinizin Toplanma Yöntemleri Yukarıda belirtilen kişisel verileriniz TEACHERA EĞİTİM KURUMLARI LİMİTED ŞİRKETİ ilettiğiniz yönteme bağlı olarak fiziki veya elektronik ortamda toplanmakta ve yukarıda belirtilen amaçlar dâhilinde işlenmekte ve aktarılmaktadır.",
      "İlgili Kişiler’in Kişisel Verileri Üzerindeki Haklarının Neler Olduğunu ve Bu Hakları Nasıl Kullanabilecekleri",
      "• KVKK m.11 uyarınca ilgili kişi sıfatıyla tarafımıza başvurarak;",
      "• Kişisel verilerinizin işlenip işlenmediğini öğrenme,",
      "• Kişisel verileriniz işlenmişse buna ilişkin bilgi talep etme,",
      "• Kişisel verilerinizin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,",
      "• Yurt içinde veya yurt dışında kişisel verilerinizin aktarıldığı üçüncü kişileri bilme,",
      "• Kişisel verilerinizin eksik veya yanlış işlenmiş olması halinde bunların düzeltilmesini isteme ve bu kapsamda yapılan",
      "işlemin kişisel verilerinizin aktarıldığı üçüncü kişilere bildirilmesini isteme,",
      "• KVKK ve ilgili diğer mevzuata uygun olarak işlenmiş olmasına rağmen; amaç, süre ve meşrutiyet prensipleri dahilinde",
      "değerlendirilmek üzere kişisel verilerinizin işlenmesini gerektiren sebeplerin ortad an kalkması halinde, kişisel verilerinizin silinmesini veya yok edilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,",
      "• İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmes i suretiyle kişinin kendisi aleyhine bir",
      "sonucun ortaya çıkmasına itiraz etme, Kişisel verilerinizin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması halinde zararın giderilmesini talep etme haklarına sahipsiniz.",
      "AYDINLATMA YÜKÜMLÜLÜĞÜ İşbu metini tebliğ almakla 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında tarafınıza aydınlatma yükümlülüğü yerine getirilmiştir.",
      "6698 sayısı Kişisel Verilerin Korunması Kanunu kapsamında, yukarıda belirtilen kişisel verilerimin işlenmesine yönelik bu aydınlatma metninde belirtilen bilgileri okudum ve anladım.",
      "VELİ KURSİYER Adı Soyadı Adı Soyadı Tarih Tarih İmza İmza teachera"
    ]
  },
  {
    "slug": "iletisim-aydinlatma-metni",
    "title": "İletişim Aydınlatma Metni",
    "shortDescription": "İletişim ve başvuru kanallarında toplanan verilerin işlenmesine ilişkin bilgilendirme metni.",
    "kind": "Aydınlatma",
    "pdfPath": "/legal/iletisim-aydinlatma-metni.pdf",
    "paragraphs": [
      "Veri Sorumlusu ve İlgili Kişi Bilgisi 6698 sayılı Kişisel Verilerin Korunması Kanunu’na göre hazırlanmış olup Teachera Eğitim Kurumları Limited Şirketi sizinle ilgili kişisel verileri işlemesi, veri işleme amaçlarını belirlemesi, veri işleme sisteminin kurulması ve işletilmesi sebebiyle veri sorumlusudur. Teachera Eğitim Kurumları Limited Şirketi tarafından, kişisel verisi işlenen gerçek kişiler, kanun tarafından ilgili kişi olarak kabul edilmektedir.",
      "Kanunun Aydınlatma Yükümlülüğünü düzenleyen 10’ncu maddesine göre, veri sorumluları, kişisel verilerini işledikleri gerçek kişileri, veri işleme ile ilgili konularda bilgilendirmekle yükümlüdür.",
      "Bu metin, ilgili kişi olarak sizi bilgilendirmeye yönelik hazırlanmış olup, ilgili kişinin (veri sahibinin) ve veri sorumlusunun hak ve yükümlülüklerini içermektedir.",
      "Veri Sorumlusunun Adı/Soyadı / Unvanı : Teachera Eğitim Kurumları Limited Şirketi Posta Adresi : Musalla Bağları Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selçuklu / Konya Telefon : 0332 236 80 66 E-posta : kvkk@teachera.com.tr İnternet Adresi : www.teachera.com.tr Kişisel Veri İşleme Amaçları ve İşlenen Veriler Öğrenci, veli, ziyaretçi, çalışan adayı, çalışan ve tedarikçilerimize yönelik, kurum güvenliğinin sağlanabilmesi, kurumumuz özel alanlarına giriş çıkışların güvenliğinin sağlanabilmesi, kurum içi yetkilendirmelerin sağlanabilmesi, ve ilgili diğer mevzuatlarının yerine getirilmesi amaçlarına yönelik olarak aşağıda belirtilen kişisel verileriniz işlenmektedir. Kişis el veriler, her türlü sözlü, yazılı ya da elektronik ortamda işbu aydınlatma metninde belirtilen amaçlar doğrultusunda toplanmaktadır.",
      "Öğrenci, veli , ziyaretçi, çalışan adayı, çalışan ve tedarikçilerimize yönelik olarak kişisel veriler,",
      "• Kanunlarda açıkça öngörülmesi,",
      "• İlgili kişinin temel hak ve özgürlüklerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri için veri",
      "işlenmesinin zorunlu olması hukuki sebeplerine dayanılarak işlenmektedir.",
      "Öğrenci, veli ,ziyaretçi, çalışan adayı, çalışan ve tedarikçilerimize yönelik işlenen veriler ise aşağıdaki kategorilerde yer alan kişisel verilerdir.",
      "• Fiziksel Mekan Güvenlik Bilgisi",
      "• Görsel ve İşitsel Veri",
      "• Kimlik Bilgisi",
      "• İletişim Bilgisi",
      "Belirtilen veri kategorilerinde hangi verilerin bulunduğu ise veri sorumlusu olarak düzenlediğimiz veri haritasında ayrıntılı olarak bulunmaktadır.",
      "İşlenen Kişisel Veriler Edinim Yöntemi İşlenen kişisel verileriniz, yazılı, sözlü, görsel ve ses kayıt sistemi ve e-posta aracılığı ile siz veri sahibinden ve üçüncü taraflardan alınmaktadır.",
      "Kişisel Veri Aktarım ve Amaçları Kişisel verileriniz KVKK Md.28/1 çerçevesinde talep edilmesi halinde aydınlatma yükümlülüğü olmadan ve açık rızanız aranmadan ilgili makamlara aktarılabilir.",
      "İşlenen kişisel veriler; hukuki uyuşmazlıkların giderilmesi veya ilgili mevzuat gereği talep halinde adli makamlar veya ilgili kolluk kuvvetlerine ya da idari makamlara kanunda öngörülen amaç̧ ve sınırlamalar dahilinde aktarılabilir.",
      "Veri Sorumlusu Hak ve Yükümlülükleri Veri sorumlusu olarak, 6698 KVKK ile diğer ilgili kanunlara uygun olarak kişisel verileri işleme, kişisel verilerin hukuka aykırı olarak işlenmesini ve erişilmesini önleme, kişisel verilerin güvenli bir şekilde işlenmesi ve muhafazası için teknik ve fili imkanlar doğrultusunda yeterli güvenlik tedbirlerini alma hak ve yükümlülükleri bulunmaktadır.",
      "Kişisel Verileri gizli tutmayı, gizliliğin sağlanması ve güvenliği için gerekli teknik ve idari her türlü tedbiri almayı ve gerekli özeni göstermeyi taahhüt etmekteyiz. Kişisel Veriler ‘in korunması kurumumuz için önemli bir konudur. Kişisel Verilere yetkisiz erişim veya bu bilgilerin kaybı, hatalı kullanımı, ifşa edilmesi, değiştirilmesi veya imha edilmesine karşı korumak için gerekli teknik ve idari her türlü önlemi alınmaktadır. Kişisel Veriler’i işlerken genel kabul görmüş güvenlik teknoloji standartları kullanmaktadır. Gerekli bilgi güvenliği önlemlerini almamıza karşın, kurumumuza ait internet sitesine ve veri işleme sistemlerimize yönelik yapılan saldırılar sonucunda Kişisel Veriler ’in zarar görmesi veya üçüncü kişilerin eline geçmesi durumunda, bu durumu derhal sizlere ve Kişisel Verileri Koruma Kurulu’na bildirir ve gerekli önlemleri alırız.",
      "Aşağıda belirtilen hususların asgari birinin olması durumunda, KVKK madde 5 ve 6 da belirtildiği üzere, açık rıza alınmasa dahi kişisel ve özel nitelikli kişisel veriler belirtilen amaçlar doğrultusunda işlenebilecektir.",
      "• İlgili kanunlarda açıkça öngörülmesi.",
      "• Bir hakkın tesisi, kullanılması veya korunması için veri işlemenin zorunlu olması.",
      "• Bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla sözleşmenin taraflarına ait kişisel verilerin",
      "islenmesinin gerekli olması.",
      "• Veri sorumlusunun hukuki yükümlülüğünü yerine getirebilmesi için zorunlu olması.",
      "• İlgili kişinin (veri sahibi) kendisi tarafından alenileştirilmiş̧ olması.",
      "• Fiili imkânsızlık nedeniyle rızasını açıklayamayacak durumda bulunan veya rızasına hukuki geçerlilik tanınmayan kişinin",
      "kendisinin ya da bir başkasının hayatı veya beden bütünlüğünün korunması için zorunlu olması.",
      "• İlgili kişinin temel hak ve özgürlüklerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri için veri",
      "işlenmesinin zorunlu olması.",
      "Sağlık ve cinsel hayata ilişkin veriler dışındaki özel nitelikli kişisel veriler (kişilerin ırkı, etnik kökeni, siyasi düşüncesi, felsefi inancı, dini, mezhebi veya diğer inançları, kılık ve kıyafeti, dernek, vakıf ya da sendika üyeliği, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili verileri ile biyometrik ve genetik verileri) açısından işlemenin kanunlarda öngörülmesi.",
      "• Sağlık ve cinsel hayata ilişkin veriler açısından kamu sağlığının korunması, koruyucu hekimlik, tıbbı teşhis, tedavi ve",
      "bakım hizmetlerinin yürütülmesi, sağlık hizmetleri ile finansmanının planlanması ve yönetimi amacıyla, sır saklama yükümlülüğü altında bulunan kişiler veya yetkili kurum ve kuruluşlar tarafından işlenmesi.",
      "Veri Sahibi Hak ve Yükümlülükleri Veri sahibi 6698 sayılı kanunun 11. Maddesinde yazılı haklara sahiptir.",
      "a) Kişisel veri işlenip işlenmediğini öğrenme, b) Kişisel verileri işlenmişse buna ilişkin bilgi talep etme, c) Kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, ç) Yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme, d) Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme, e) 7nci maddede öngörülen şartlar çerçevesinde kişisel verilerin silinmesini veya yok edilmesini isteme, f) (d) ve (e) bentleri uyarınca yapılan işlemlerin, kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, g) İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme, ğ) Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini talep etme, Talep ve Başvuru Yukarıda belirtilen tüm haklarınızı kullanmak için başvuru formunu ve kullanmak istediğiniz hakka ilişkin açıklamalarınızı içeren metni, Musalla Bağları Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selçuklu / Konya adresine ıslak imzalı nüshasını kimliğinizi tespit edici belgeler ile iletebilir.",
      "• kvkk@teachera.com.tr e-posta adresine iletebilir veya,",
      "• www.teachera.com.tr adresinde bulunan Veri Sahibi başvuru formu ile iletebilirsiniz.",
      "Yukarıda belirtilen şekillerden biri ile imzalanmak suretiyle gönderebilirsiniz.",
      "Talebiniz bize ulaştıktan sonra 30 gün içerisinde sizlere burada belirtilen kanallardan geri dönüş yapılarak bilgilendirme yapılacaktır.",
      "Kişisel Verileri Koruma Kurumu tarafından getirilecek yeni düzenlemeler kapsamında gelecekte vuku bulacak tüm gelişmelere göre aydınlatma metnin de değişiklik yapma hakkımız saklıdır.",
      "AYDINLATMA YÜKÜMLÜLÜĞÜ İşbu metini tebliğ almakla 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında tarafınıza aydınlatma yükümlülüğü yerine getirilmiştir.",
      "6698 sayısı Kişisel Verilerin Korunması Kanunu kapsamında, yukarıda belirtilen kişisel verilerimin işlenmesine yönelik bu aydınlatma metninde belirtilen bilgileri tüm öğrenci, veli ,ziyaretçi, çalışan adayı, çalışan, tedarikçilerimiz için geçerlidir."
    ]
  },
  {
    "slug": "cagri-merkezi-aydinlatma-metni",
    "title": "Çağrı Merkezi Aydınlatma Metni",
    "shortDescription": "Çağrı merkezi süreçlerinde işlenen veriler ve ilgili kişi haklarına dair bilgilendirme metni.",
    "kind": "Aydınlatma",
    "pdfPath": "/legal/cagri-merkezi-aydinlatma-metni.pdf",
    "paragraphs": [
      "CAGRI MERKEZI AYDINLATMA METNI Veri Sorumlusu: Teachera Egitim Kurumlari Limited Sirketi Adres: Musalla Baglari Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selcuklu / Konya Telefon: 0332 236 80 66 E-posta: kvkk@teachera.com.tr Web: www.teachera.com.tr",
      "1. Islenen Veri Kategorileri",
      "Cagri merkezi sureclerinde kimlik, iletisim, cagrinin konusu, talep/sikayet icerigi, gorusme kaydi ve islem loglari islenebilir.",
      "2. Isleme Amaclari",
      "Talep ve sikayet yonetimi, hizmet kalitesinin artirilmasi, is surekliliginin saglanmasi, hukuki yukumluluklerin yerine getirilmesi ve bilgi guvenligi amaclariyla veri islenir.",
      "3. Hukuki Sebepler",
      "Veriler, KVKK madde 5 kapsaminda sozlesmenin kurulmasi/ifasi, hukuki yukumluluklerin yerine getirilmesi ve veri sorumlusunun mesru menfaatleri hukuki sebeplerine dayanilarak islenir.",
      "Gerekli oldugunda acik riza alinabilir.",
      "4. Aktarim ve Saklama",
      "Veriler, mevzuatin izin verdigi olcude yetkili kurum/kuruluslar ve hizmet saglayicilarla paylasilabilir. Saklama sureleri ilgili mevzuata ve isleme amacina gore belirlenir.",
      "5. Veri Sahibi Haklari",
      "KVKK madde 11 kapsamindaki haklarinizi kullanmak icin kvkk@teachera.com.tr adresine basvurabilirsiniz."
    ]
  },
  {
    "slug": "ilgili-kisi-basvuru-formu",
    "title": "İlgili Kişi Başvuru Formu",
    "shortDescription": "KVKK kapsamındaki başvuru, talep ve hak kullanımı süreçleri için resmi başvuru formu.",
    "kind": "Form",
    "pdfPath": "/legal/ilgili-kisi-basvuru-formu.pdf",
    "paragraphs": [
      "VERİ SAHİBİ TALEP FORMU Doküman No FR-KVKK-04 Ilk Yayın Tarihi 14.03.2023 Revizyon No Revizyon Tarihi Formu Teslim Alan KVKK İletişim Kişisi Kontrol/Onaylayan Genel Müdür 1/1 Kişisel Verilerin Korunması Kanunu’ndan (KVKK) doğan haklarını kullanmak isteyen kişilerin bu formu doldurarak aşağıdaki yöntemlerden biri aracılığıyla kurumumuza ulaştırması gerekmektedir.",
      "i. Kimlik belgesi (Nüfus Cüzdanı, Ehliyet, Pasaport vb.) ile kurumumuza bizzat başvurarak ii. Musalla Bağları Mah. Kule Cad. Selcuklu Kulesi No: 2 / 42 Selçuklu / Konya adresine göndererek iii. kvkk@teachera.com.tr adresine veri sahibinin e-posta adresinden ileterek Talebiniz bize ulaştıktan sonra 30 gün içerisinde sizlere burada belirtilen kanallardan geri dönüş yapılarak bilgilendirme yapılacaktır.",
      "1. Veri Sahibine Yönelik Bilgiler",
      "Ad/Soyadı TC Kimlik Numarası Telefon Numarası Eposta Adres",
      "2. Başvuruda Bulunan",
      "Şirketimiz ile olan ilişkinizi en uygun şekilde tanımlayan seçeneği işaretleyip, detay bilgi alanına bu ilişkinin devam durumunu, sona ermiş olması durumunda ilişkinin vuku bulduğu periyodu belirtiniz.",
      "Müşteri Ziyaretçi Çalışan Adayı Tedarikçi Çalışan Diğer* Diğer (Açıklama):",
      "3. KVKK kapsamındaki talebinizi lütfen detaylandırınız:",
      "…………………………………………………………………………………………………………………………… …………………………………………………………………………………………………………………………… …………………………………………………………………………………………………………………………… …………………………………………………………………………………………………………………………… …………………………………………………………………………………………………………………………… ……………………………",
      "4. Başvurunun Sonuçlandırmasına Yönelik Bilgiler",
      "Geri dönüş kanalı konusunda özel bir tercihiniz varsa lütfen belirtiniz. Talebinizin değerlendirilmesi için ek bilgiye ihtiyaç duyulması halinde sizinle iletişim kurulabilecektir.",
      "Posta Eposta Veri Sahibi İmzası teachera"
    ]
  },
  {
    "slug": "uyelik-sozlesmesi",
    "title": "Üyelik Sözleşmesi",
    "shortDescription": "Platform üyeliğinde tarafların temel hak ve yükümlülüklerine ilişkin sözleşme metni.",
    "kind": "Sözleşme",
    "pdfPath": "/legal/uyelik-sozlesmesi.pdf",
    "paragraphs": [
      "UYELIK SOZLESMESI Bu metin, Teachera platformu uzerinden sunulan hizmetlere uyelik surecinde taraflarin temel hak ve yukumluluklerini genel cercevede duzenlemek amaciyla hazirlanmistir.",
      "Uyelik olusturan kullanici; paylastigi bilgilerin dogru ve guncel oldugunu, hesap guvenliginden sorumlu oldugunu ve hizmet kullaniminda yururlukteki mevzuata uygun hareket edecegini kabul eder.",
      "Kurum, hizmet surecinin yurutulmesi ve yasal yukumluluklerin yerine getirilmesi kapsaminda gerekli teknik ve idari tedbirleri uygular. Kisisel verilerin islenmesine iliskin detaylar ilgili aydinlatma metinlerinde yer alir.",
      "Kullanici, gerekli durumlarda uyeligini sonlandirma veya destek talebi olusturma hakkina sahiptir. Iletisim: data@teachera.com.tr ve 0332 236 80 66.",
      "Isbu metin taslak bilgilendirme dokumani niteligindedir. Nihai hukuki metin kurum tarafindan guncellenebilir."
    ]
  }
];

export const LEGAL_DOCUMENT_MAP: Record<string, LegalDocumentData> = Object.fromEntries(
  LEGAL_DOCUMENTS.map((doc) => [doc.slug, doc]),
);
